apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: serv-ingress
  namespace: jenkins
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /myapp
        backend:
          serviceName: dev-service
servicePort: 3000
