apiVersion: v1
kind: Service
metadata:
  name: dev-service
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      name: "http"
      nodePort: 31000
      targetPort: 8080
      protocol: TCP
  selector:
    app: dev-service
